version: '3.8'

services:
  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    env_file:
      - ~/.sqlmate/secrets.env
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    environment:
      - BACKEND_URL=http://backend:8080
    ports:
      - "3000:3000"
