CREATE_USERS_TABLE = """
CREATE TABLE IF NOT EXISTS sqlmate.users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""

CREATE_USER_TABLES_TABLE = """
CREATE TABLE IF NOT EXISTS sqlmate.user_tables (
	user_id INT NOT NULL,
	table_name VARCHAR(100) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (user_id, table_name),
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
"""

CREATE_TABLES_TO_DROP_TABLE = """
CREATE TABLE IF NOT EXISTS sqlmate.tables_to_drop (
	user_id INT NOT NULL,
	table_name VARCHAR(100) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (user_id, table_name)
);
"""